title: "Nour Gnich"
description: "Data Science & Business Intelligence · Marketing Analytics"
theme: minima
minima:
  skin: dark

# Personalize these before you push
author: "Nour Gnich"
email: "nourgn076@gmail.com"
linkedin: "https://www.linkedin.com/in/nourgnich"
github_username: "nourgn076-cmyk"

markdown: kramdown
plugins:
  - jekyll-feed

# This makes README.md render as your homepage (slide 18, step 3)
show_excerpts: false
